namcibc.c/visae: Greetings

on: [pcibc.com/visa.refund, //4 thomas.huntrefunde back,into, my BMO account, after taking all my ODSP money,and applied it to a
Visa bill that I owed, without any//no permission, whatsoever, .and left me with, nothing, no money to pay my rent.my refund from CIBC, should be 2,000ull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
